### ISSUE TITLE
Covers doesn't disapear

### ISSUE THREAD

**Issue by jmarcelomb** [mathewmeconry/MMM-HomeAssistant-Touch#5]
Hi!!

I'm having a problem that sometimes (most of the times) doesn't disappear the slider when I use my cover, and I can't make it disappear. If I click again, it follows my mouse.

![image](https://user-images.githubusercontent.com/35546901/162028580-b86aa6cb-fa29-4e47-903f-7fb1b3dafa90.png)

**Comment by mathewmeconry** [comment]
Hey
I pushed a possible fix in the branch `fix/stale_sliders`. Can you try that one out?

**Comment by jmarcelomb** [comment]
Hi, thank you for you fast response, I tried and it still happens:
![image](https://user-images.githubusercontent.com/35546901/162157522-0a9b1301-5779-4a4f-9f4f-c41e08738b04.png)

**Comment by mathewmeconry** [comment]
hmmm... can you give me a way how to reproduce it?
maybe sliding the finger differently, multitouch or something like this

**Comment by jmarcelomb** [comment]
There is a way to give you a log or something?

**Comment by mathewmeconry** [comment]
I added some logging to the same branch. can you reproduce it and send me the logs?

**Comment by jmarcelomb** [comment]
I pull and right now I can't reproduce the bug but If it happens again I will tell you.

Thank you for the attention!!

**Comment by mathewmeconry** [comment]
@jmmb13 I assume my fix branch works correctly now?
If so I would like to merge this fix and make it available to everybody

**Comment by jmarcelomb** [comment]
I didn't use it any more, I'm sorry.

**Comment by mathewmeconry** [comment]
ok than I close the issue and delete the branch
